# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-07 07:33
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200607_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post',
            field=tinymce.models.HTMLField(default=None),
        ),
    ]
